# This is a basic workflow to help you get started with Actions .

name: auto-deployment-react-context&useReducer

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Deploying to surge
    steps:
      - uses: actions/checkout@v2
      - name: Installing Node.js
        uses: actions/setup-node@v2-beta
        with:
          node-version: 12

      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install # will run `yarn install` command
      - name: Build React App
        run: yarn build
      - name: Install Surge
        run: npm install -g surge
      - name: Run surge
      run: surge ./build react-context-usereducer-demo-2020.surge.sh --token ${{ secrets.SURGE_TOKEN2 }}
